### PR TITLE
created tests

### PR DESCRIPTION
**Pull request by hamishgibbs**
Created tests for function returns.

### CODE REVIEW

**Comment by hamishgibbs** [comment]
Not clear to me why build is failing - rebuilt docs which resolved issue last time.

**Comment by hamishgibbs** [comment]
get_japan_regional_cases fails when reading html document from cache (but not when reading from https). Temporarily replaced caching functionality with xml2::read_html while I find a fix.

**Review by seabbs — APPROVED** [review]
All looks good - good job! `memoise` is not a big deal I think. We mainly needed it for the google spreadsheets that couldn't always be accessed and because we were hitting some data sources again and again (not a great idea). We could think about moving away from it entirely but would need to canvas opinion on that as it is quite a big change.

**Comment by hamishgibbs** [comment]
I think `memoise` keeps things quick for the functions that do more processing or read from multiple urls so I support keeping it. But I believe there was come conflict in the way that `memoise` stored the raw html for get_japan_regional_cases. I think the issue could be fixed by wrapping the whole data scraping/cleaning into a function and caching the output of that. But not super important as the dataset is not very large.

**Comment by seabbs** [comment]
Agree and good idea!

**Comment by seabbs** [comment]
Also agree not an absolute priority

**Pull request merged**
