### PR TITLE
remove tibble dependency

### PR DESCRIPTION
**Pull request by hamishgibbs**
Removed `tibble` dependency by changing `tibble::tibble` to `dplyr::tibble` and `tibble::as_tibble` to `dplyr::as_tibble`. Also rewrote `tibble::enframe` in get_japan_regional_cases to rely only on `dplyr`.

### CODE REVIEW

**Comment by seabbs** [comment]
I think this doesn't do what is expected as dplyr depends on tibble for this functionality? Happy to be wrong

**Comment by hamishgibbs** [comment]
You are right, `dplyr` depends on `tibble` for `tibble::tibble` and `tibble::as_tibble`. Is it better to rely on dplyr to have tibble as a dependency?

So that we do not import tibble in this package when it is already a dependency of dplyr?

Or does that not make too much difference?

**Comment by seabbs** [comment]
It doesn't really make a difference our deps just go `dplyr` -> `tibble` rather than straight to `tibble`. In general I like to err on the side of clarity so would rather stick with dep on `tibble`. Sorry!

**Comment by seabbs** [comment]
(suggest closing 🔓 )

**Comment by hamishgibbs** [comment]
That sounds good, no need to use tibble through dplyr!

**Pull request closed without merging**
