### PR TITLE
vignette

### PR DESCRIPTION
**Pull request by kathsherratt**
Created a brief vignette in to show different package functions (basically a more readable version of the README), with Germany as an example. Edits welcome

### CODE REVIEW

**Comment by seabbs** [comment]
Nice. 

Vignette needs to live in a vignettes folder when using a package :). I imagine that is what is causing the Travis to build failure!

**Comment by seabbs** [comment]
Perhaps we should just have this to flesh out the README though?

**Comment by kathsherratt** [comment]
Sorry! Agreed, happy to have it in the README, basically just thought it would be good to have something that explains what's going on a little clearer.

**Comment by seabbs** [comment]
100% agree

**Pull request closed without merging**
