### PR TITLE
add get_france_regional_cases function

### PR DESCRIPTION
**Pull request by PaulC91**
Data pulled from daily SPF yaml file data here: https://github.com/opencovid19-fr/data/tree/master/sante-publique-france

### CODE REVIEW

**Comment by seabbs** [comment]
Awesome this looks great. Thanks for the contribution!

Build failure looks to be an issue with the ECDC function and nothing on your end. Could you add a   limited test (along the lines of those for `get_ecdc_cases`) if you have a chance?

Also, can I have your details to add as a contributor (if your happy with that)

**Comment by PaulC91** [comment]
Hi Sam. Sure no problem, added a small test.

We just started using the package at Epicentre MSF but needed regional french data so I thought I'd put in a pull request. We're probably going to maintain our own fork going forward but will pull request as and when we have anything new if you're interested.

My email is paul.campbell@epicentre.msf.org. Let me know if you need any more details for contributor info.

Cheers!

Paul

**Comment by seabbs** [comment]
Hi Paul, 

Excellent and sounds good. Very keen to have more data sources etc. 

Have a good weekend (hopefully not as worked filled as mine!)

Sam

**Review by seabbs — COMMENTED** [review]
Looks good

**Review by seabbs — APPROVED** [review]

**Comment by PaulC91** [comment]
Yeah never been busier but better that than the opposite in these times!

Have a good one also, with hopefully some rest!

Paul

**Pull request merged**
