### PR TITLE
Fetches case counts by NHS region (currently only England). Added sma…

### PR DESCRIPTION
**Pull request by seabbs**
…ll shape files to data-raw that are used to add ONS region codes to the data that will make mapping much easier in the long run.

### CODE REVIEW

**Comment by seabbs** [comment]
So this looks like it will only work in the root directory of the package and not elsewhere which we currently need. 

This also only does cases in England are Wales, Scotland and Northern Ireland not possible/present?

It would also be nice to have `memoise` as for the other functions implemented. 😸 

Also passing on Travis please ...

**Comment by seabbs** [comment]
What needs to happen here to get this off the ground? Very happy to do the drudge work.

**Comment by jhellewell14** [comment]
- Removed shape files from package
- Function pulls data for English NHS regions, Scottish NHS regions, Wales, Northern Ireland
- Travis build failed but it's not my fault

**Comment by jhellewell14** [comment]
I made a complimentary shape file that combines NHS regions in Engand and Scotland as well as country-wide shapefiles for Northern Ireland and Wales. The data fetching function now auto-completes any of the regions in the shapefiles that might be missing with 0s. Names produced by the fetching function exactly match the shape file names for easy plotting.

**Pull request merged**
