### PR TITLE
ECDC data formatting function

### PR DESCRIPTION
**Pull request by jhellewell14**
* Wrote function to format ECDC data for EpiNow analysis
* Added basic tests for function
* Removed tabulizer from DESCRIPTION while get_spain_regional_cases is not in use (lots of further dependencies on Java and makes requirements much higher for package)

### CODE REVIEW

**Review by seabbs — CHANGES_REQUESTED** [review]
Looks good - nice one. Can you add to the pkgdown yml somewhere sensible please so it shows up in the docs?

**Comment by jhellewell14** [comment]
Added to pkgdown: https://github.com/epiforecasts/NCoVUtils/pull/41/commits/70e83b744f299f8afa196788211922d9de2e8442

**Review by seabbs — APPROVED** [review]
Looks good.

**Comment by seabbs** [comment]
Boom son. Just waiting on Travis

**Pull request merged**
