### PR TITLE
Reset cache changes

### PR DESCRIPTION
**Pull request by hamishgibbs**
Get reset_cache to refresh all available data sources. This is not a complete reload of the cache for functions with multiple arguments. Those functions could be ignored in reset_cache or could be included with all parameter combinations?

Also, not sure if this change is necessary, there are now a lot of available data sources.

### CODE REVIEW

**Comment by seabbs** [comment]
Hmm good point. I think it might make sense to just have this delete the cache and leave updates to calling each function. What do you think?

**Review by seabbs — COMMENTED** [review]
Looks good. Just waiting on Travis

**Comment by hamishgibbs** [comment]
Travis failed last time because of same issue with `get_japan_regional_cases()` that was unresolved in this branch. Hopefully merge solved the issue

**Comment by hamishgibbs** [comment]
It is a small change and there are many unresolved conflicts in this branch. Will close this request and reopen on clean branch.

**Pull request closed without merging**
