### PR TITLE
Fix get_interventions_data

### PR DESCRIPTION
**Pull request by kathsherratt**
Fixed error: `Error: Evaluation error: error -103 with zipfile in unzGetCurrentFileInfo`
By adding `mode = 'wb'` to options in file.download

### CODE REVIEW

**Review by seabbs — CHANGES_REQUESTED** [review]
Seeing a build failure?  Looks like `get_interventions` is failing its tests

**Comment by seabbs** [comment]
Sigh this data is annoying isn't it. Seeing this test failure which is quite opaque: 

```
── 1. Error: get_interventions_data works as expected (@test-get_interventions_d
1246A '::id' rule specifies an unknown transliterator. (U_INVALID_ID)
1247Backtrace:
1248  1. NCoVUtils::get_interventions_data()
1249  2. readxl::read_excel(file.path(temp, filename), sheet = "Database")
1250  9. janitor::clean_names(.)
1251 12. janitor::make_clean_names(names(dat), ...)
1252 13. stringi::stri_trans_general(replaced_names, id = "Greek-Latin;Latin-ASCII;Accents-Any;Any-ASCII")── 1. Error: get_interventions_data works as expected (@test-get_interventions_d
1246A '::id' rule specifies an unknown transliterator. (U_INVALID_ID)
1247Backtrace:
1248  1. NCoVUtils::get_interventions_data()
1249  2. readxl::read_excel(file.path(temp, filename), sheet = "Database")
1250  9. janitor::clean_names(.)
1251 12. janitor::make_clean_names(names(dat), ...)
1252 13. stringi::stri_trans_general(replaced_names, id = "Greek-Latin;Latin-ASCII;Accents-Any;Any-ASCII")
```

**Comment by PaulC91** [comment]
Looks to be coming from a missing translator janitor::clean_names is looking for. The raw names are pretty clean but in all caps. @kathsherratt could switch from janitor::clean_names to something like `names(df) <- tolower(names(df))` and see if that fixes the test failure? thanks

**Comment by kathsherratt** [comment]
Thanks very much Paul and Sam. Updated to remove janitor dependency, and added return() to function. Hopefully this is now fixed, looks like it is passing checks

**Review by seabbs — APPROVED** [review]
Nice

**Pull request merged**
